Repository gangjun06/NovelAI.app, pull requests merged in 2022-10, with the labels that each got.

#2 feat: 다크모드 지원
  src/components/DarkModeToggle.tsx
  src/components/Home.tsx
  src/components/NSFWToggle.tsx
  src/components/ResultBar.tsx
  src/components/Tag.tsx
  src/components/TagCard.tsx
  src/components/index.tsx
  src/styles/globals.css
  tailwind.config.js
Labels: enhancement, good first issue

#6 chore: setup storybook
  .storybook/main.js
  .storybook/preview.js
  package.json
  src/Introduction.stories.mdx
  src/components/Common/Button/Button.stories.tsx
  src/components/Common/Button/Button.tsx
  src/pages/_app.tsx
  src/styles/globals.scss
  yarn.lock
Labels: enhancement

#14 feat: Tag 컴포넌트 표현 개선
  src/components/Home.tsx
  src/components/NSFWToggle.tsx
  src/components/PromptToggle.tsx
  src/components/ResultBar.tsx
  src/components/Tag.tsx
  src/components/TagCard.tsx
Labels: enhancement, good first issue

#21 docs: add issue and pr template
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/docs.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
Labels: Type: Documentation

#23 [FEAT] 태그 생성기 레이아웃 변경
  next.config.js
  package.json
  src/assets/tags.json
  src/components/ResultBar.tsx
  src/components/TagCard.tsx
  src/components/atoms/Icons/Icons.tsx
  src/components/atoms/Switch/Switch.tsx
  src/components/atoms/Tag/Tag.tsx
  src/components/atoms/index.tsx
  src/components/index.tsx
  src/components/molecule/Menu/Menu.tsx
  src/components/molecule/Modal/Modal.tsx
  src/components/organizm/MainNav/MainNav.tsx
  src/components/organizm/SettingModal/SettingModal.tsx
  src/components/organizm/TagTool/Content/Card.tsx
  src/components/organizm/TagTool/Content/Content.tsx
  src/components/organizm/TagTool/Library/Categories.tsx
  src/components/organizm/TagTool/Library/Category.tsx
  src/components/organizm/TagTool/Library/Library.tsx
  src/components/organizm/TagTool/Library/Modals/AddCategoryModal.tsx
  src/components/organizm/TagTool/Library/Tag.stories.tsx
  src/components/organizm/TagTool/Library/Tag.tsx
  src/components/organizm/TagTool/TagTool.tsx
  src/components/organizm/TagTool/atoms.ts
  src/components/pages/Home.tsx
  src/components/template/Main/MainTemplate.tsx
  src/hooks/useDisclosure.ts
  src/hooks/useElementSize.ts
  src/hooks/useResponsiveGrid.ts
  src/hooks/useSetting.ts
  src/hooks/useWindowSize.ts
  src/pages/_app.tsx
  src/styles/globals.scss
  src/utils/multipleContainersKeyboardCoordinates.ts
  src/utils/text.tsx
  tailwind.config.js
  yarn.lock
Labels: Type: Feature, Status: In Progress
